version: '3'

services:
  app:
    build: .
    ports: 
      - 8000:80
      - 8001:443
    volumes:
      - CAMINHO_CERTIFICADO:/https/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SENHA_CERTIFICADO
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    command: 
      ["dotnet", "MrMoney.API.dll"]